Reordered functions for legibility.

diff --git a/files/bin/nethack b/files/bin/nethack
--- a/files/bin/nethack
+++ b/files/bin/nethack
@@ -24,6 +24,38 @@ puke_recursion_count=0
 self_short_name="$(sed 's/^.*\///g' <<< "${0}")"
 
 
+play() {
+  if nethack_is_running; then
+    puke 1 "You're playing enough nethack for now."
+  fi
+  recover
+  mount_remote_bones_dir
+  lock_dir $remote_bones_dir
+  upload_bones_files
+  download_bones_files
+  unlock_dir $remote_bones_dir
+  unmount_remote_bones_dir
+  if mesg >/dev/null; then mesg=y; else mesg=n; fi
+  mesg n
+  echo "Starting nethack."
+  $nethack
+  echo "nethack returned:  $?"
+  mesg "${mesg}"
+  unlock_local_bones_files
+  mount_remote_bones_dir
+  lock_dir $remote_bones_dir
+  report_consumed_bones_files
+  post_game=1 upload_bones_files
+  unlock_dir $remote_bones_dir
+  unmount_remote_bones_dir
+}
+
+
+nethack_is_running() {
+  grep "${nethackdir}/nethack" <<< $(ps -elf) | awk '{print $3}' | grep -q "^${USER}"'$'
+}
+
+
 puke() {
   puke_recursion_count=$(( puke_recursion_count + 1 ))
   ret=$1
@@ -37,6 +69,39 @@ puke() {
     echo "DOUBLE BLEAH:  ${@}"
   fi
   exit $ret
+}
+
+
+recover() {
+  if nethack_is_running; then
+    puke 1 "Attempted to recover while a game is active."
+  fi
+  bases=(
+    $(
+      find "${nethackdir}" -user "${USER}" \
+      | sed 's/^.*\///g' \
+      | grep -v '^\.' \
+      | grep lock \
+      | sed 's/\..*$//' \
+      | uniq
+    )
+  )
+  if test 0 -lt "${#bases[@]}"; then
+    echo "Recovering games - base names:"
+    for base in "${bases[@]}"; do
+      echo "  '${base}'"
+    done
+    "${nethackdir}"/recover -d "${nethackdir}" "${bases[@]}"
+    echo "Recovery finished.  Results not checked."
+  else
+    echo "No games to recover."
+  fi
+  # What is this supposed to do?  There was actually no file at this location
+  # when chown was attempted.  Recovery seemed to go fine, though.
+  for base in "${bases[@]}"; do
+    echo "Adjusting permissions for:  '${base}'"
+    chown :games "${nethackdir}"/"${base}"
+  done
 }
 
 
@@ -54,6 +119,18 @@ mount_remote_bones_dir() {
 unmount_remote_bones_dir() {
   fusermount -u $remote_bones_dir || puke $? "Failed to unmount remote shared bones."
   rmdir $remote_bones_dir || puke $? "Failed to remove mount point for remote shared bones."
+}
+
+
+lock_dir() {
+  dir="${1}"
+  lock "${dir}/${lock_dir}"
+}
+
+
+unlock_dir() {
+  dir="${1}"
+  unlock "${dir}/${lock_dir}"
 }
 
 
@@ -78,6 +155,20 @@ lock() {
 }
 
 
+unlock() {
+  file_lock_dir="${1}"
+  rm "${file_lock_dir}/pid.${$}" || puke $? "Failed to remove PID file:  ${file_lock_dir}/pid.${$}"
+  rmdir "${file_lock_dir}" || puke $? "Failed to remove lock dir:  ${file_lock_dir}"
+  locks_backup=("${locks[@]}")
+  locks=()
+  for lock in "${locks_backup[@]}"; do
+    if ! test "${file_lock_dir}" == "${lock}"; then
+      locks+=( $lock )
+    fi
+  done
+}
+
+
 kick_lock() {
   file_lock_dir="${1}"
   for pid_file in ${file_lock_dir}/pid.*; do
@@ -97,42 +188,9 @@ kick_lock() {
 }
 
 
-lock_dir() {
-  dir="${1}"
-  lock "${dir}/${lock_dir}"
-}
-
-
 kick_lock_dir() {
   dir="${1}"
   kick_lock "${dir}/${lock_dir}"
-}
-
-
-unlock() {
-  file_lock_dir="${1}"
-  rm "${file_lock_dir}/pid.${$}" || puke $? "Failed to remove PID file:  ${file_lock_dir}/pid.${$}"
-  rmdir "${file_lock_dir}" || puke $? "Failed to remove lock dir:  ${file_lock_dir}"
-  locks_backup=("${locks[@]}")
-  locks=()
-  for lock in "${locks_backup[@]}"; do
-    if ! test "${file_lock_dir}" == "${lock}"; then
-      locks+=( $lock )
-    fi
-  done
-}
-
-
-unlock_dir() {
-  dir="${1}"
-  unlock "${dir}/${lock_dir}"
-}
-
-
-lock_file() {
-  file="${1}"
-  file_lock_dir=$(sed -E 's/\/([^\/]*)$/\/.lock.\1/' <<< $file)
-  lock $file_lock_dir
 }
 
 
@@ -140,6 +198,13 @@ kick_lock_file() {
   file="${1}"
   file_lock_dir=$(sed -E 's/\/([^\/]*)$/\/.lock.\1/' <<< $file)
   kick_lock $file_lock_dir
+}
+
+
+lock_file() {
+  file="${1}"
+  file_lock_dir=$(sed -E 's/\/([^\/]*)$/\/.lock.\1/' <<< $file)
+  lock $file_lock_dir
 }
 
 
@@ -160,46 +225,6 @@ unlock_local_bones_files() {
   for bones_file in "${checked_out_bones_files[@]}"; do
     unlock_file $nethackdir/$bones_file
   done
-}
-
-
-register() {
-  bones_entry="${1}"
-  if ! grep -q "${bones_entry}" "${bones_registries[@]}"; then
-    lock_file $bones_registry
-    echo "${bones_entry}" >> $bones_registry || puke $? "Failed to register bones (${bones_entry}) in:  ${bones_registry}"
-    unlock_file $bones_registry
-  fi
-}
-
-
-unregister() {
-  bones_entry="${1}"
-  lock_file $bones_registry
-  > "${bones_registry}.tmp" || puke $? "Failed to create/blank temporary file:  ${bones_registry}.tmp"
-  touch $bones_registry || puke $? "Failed to touch:  ${bones_registry}"
-  # Don't fail if grep fails.  The bones registry may be empty.
-  grep -v "^${bones_entry}\$" $bones_registry > "${bones_registry}.tmp"
-  mv $bones_registry.tmp $bones_registry || puke $? "Failed to overwrite bones registry."
-  unlock_file $bones_registry
-}
-
-
-report_consumed_bones_files() {
-  for bones_file in "${checked_out_bones_files[@]}"; do
-    if ! test -e $nethackdir/$bones_file; then
-      bones_entry=$(bones_entry "${nethackdir}" "${bones_file}")
-      echo "       Consumed:  ${bones_entry}"
-      unregister "${bones_entry}"
-    fi
-  done
-}
-
-
-bones_entry() {
-  dir="${1}"
-  bones_entry="${2}"
-  echo "$(stat -c %y "${dir}/${bones_file}" | sed 's/\.[0-9]*//') - ${bones_file}"
 }
 
 
@@ -281,68 +306,43 @@ download_bones_files() {
 }
 
 
-nethack_is_running() {
-  grep "${nethackdir}/nethack" <<< $(ps -elf) | awk '{print $3}' | grep -q "^${USER}"'$'
-}
-
-
-play() {
-  if nethack_is_running; then
-    puke 1 "You're playing enough nethack for now."
-  fi
-  recover
-  mount_remote_bones_dir
-  lock_dir $remote_bones_dir
-  upload_bones_files
-  download_bones_files
-  unlock_dir $remote_bones_dir
-  unmount_remote_bones_dir
-  if mesg >/dev/null; then mesg=y; else mesg=n; fi
-  mesg n
-  echo "Starting nethack."
-  $nethack
-  echo "nethack returned:  $?"
-  mesg "${mesg}"
-  unlock_local_bones_files
-  mount_remote_bones_dir
-  lock_dir $remote_bones_dir
-  report_consumed_bones_files
-  post_game=1 upload_bones_files
-  unlock_dir $remote_bones_dir
-  unmount_remote_bones_dir
-}
-
-
-recover() {
-  if nethack_is_running; then
-    puke 1 "Attempted to recover while a game is active."
-  fi
-  bases=(
-    $(
-      find "${nethackdir}" -user "${USER}" \
-      | sed 's/^.*\///g' \
-      | grep -v '^\.' \
-      | grep lock \
-      | sed 's/\..*$//' \
-      | uniq
-    )
-  )
-  if test 0 -lt "${#bases[@]}"; then
-    echo "Recovering games - base names:"
-    for base in "${bases[@]}"; do
-      echo "  '${base}'"
-    done
-    "${nethackdir}"/recover -d "${nethackdir}" "${bases[@]}"
-    echo "Recovery finished.  Results not checked."
-  else
-    echo "No games to recover."
-  fi
-  # What is this supposed to do?  There was actually no file at this location
-  # when chown was attempted.  Recovery seemed to go fine, though.
-  for base in "${bases[@]}"; do
-    echo "Adjusting permissions for:  '${base}'"
-    chown :games "${nethackdir}"/"${base}"
+report_consumed_bones_files() {
+  for bones_file in "${checked_out_bones_files[@]}"; do
+    if ! test -e $nethackdir/$bones_file; then
+      bones_entry=$(bones_entry "${nethackdir}" "${bones_file}")
+      echo "       Consumed:  ${bones_entry}"
+      unregister "${bones_entry}"
+    fi
   done
+}
+
+
+register() {
+  bones_entry="${1}"
+  if ! grep -q "${bones_entry}" "${bones_registries[@]}"; then
+    lock_file $bones_registry
+    echo "${bones_entry}" >> $bones_registry || puke $? "Failed to register bones (${bones_entry}) in:  ${bones_registry}"
+    unlock_file $bones_registry
+  fi
+}
+
+
+unregister() {
+  bones_entry="${1}"
+  lock_file $bones_registry
+  > "${bones_registry}.tmp" || puke $? "Failed to create/blank temporary file:  ${bones_registry}.tmp"
+  touch $bones_registry || puke $? "Failed to touch:  ${bones_registry}"
+  # Don't fail if grep fails.  The bones registry may be empty.
+  grep -v "^${bones_entry}\$" $bones_registry > "${bones_registry}.tmp"
+  mv $bones_registry.tmp $bones_registry || puke $? "Failed to overwrite bones registry."
+  unlock_file $bones_registry
+}
+
+
+bones_entry() {
+  dir="${1}"
+  bones_entry="${2}"
+  echo "$(stat -c %y "${dir}/${bones_file}" | sed 's/\.[0-9]*//') - ${bones_file}"
 }
 
 
